### ISSUE TITLE
TmdlFormatException since upgrading 2.21.1 

### ISSUE THREAD

**Issue by matt40k** [TabularEditor/TabularEditor#1155] opened 2023-11-14 14:19 UTC
**Describe the bug**
Unable to open data model from folder after upgrading to 
Tabular Editor 2.21.1 (build 2.21.8718.23075)

Worked ok in Tabular Editor 2.20.2 (build 2.20.8651.25824)

Error is:
##[error]Error loading file: TmdlFormatException encountered while deserializing TMDL: TMDL Format Error: [UnsupportedPropertyName] incrementalGranularity

Simple example:

```
table 'New Table'
	lineageTag: d866c562-e608-4c86-9def-3082b8f3645e
	refreshPolicy:
		policyType: Basic
		rollingWindowGranularity: Month
		rollingWindowPeriods: 1
		incrementalGranularity: Day
		incrementalPeriods: 1

	partition 'New Table' = Query
		dataSource: 'New Provider Data Source'
```

**Comment by DBojsen** [comment] 2023-11-14 14:47
Hi @matt40k 

I'm quite sure that is because [2.21.1](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.1) is using the latest AMO/TOM libraries from Microsoft and they unfortunately include breaking changes from earlier versions. (and is still in preview)

Best workaround now is to open with the last working version (you can use the portable version: [TabularEditor.2.20.2.zip](https://cdn.tabulareditor.com/files/TabularEditor.2.20.2.zip)) and same as model.bim or TE's Save-to-folder format and afterwards reopen in the latest version and save as TMDL again.

**Comment by otykier** [comment] 2023-11-14 14:48
Agree with @DBojsen. If the deserialization still doesn't work in 2.21.1, after saving the model as TMDL using the same version, please open a support ticket with Microsoft, as all TMDL serialization/deserialization is handled by [their library](https://www.nuget.org/packages/Microsoft.AnalysisServices.Tabular.Tmdl.retail.amd64).

**Comment by matt40k** [comment] 2023-11-14 16:48
Yer its broke in the Microsoft library - 19.69.6.2-TmdlPreview
Works ok for 19.69.2.2-TmdlPreview.

just did a simple:

```
using Microsoft.AnalysisServices.Tabular;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main()
        {
            var t = TmdlSerializer.DeserializeModelFromFolder("C:\\source\\repos\\clarity-powerbi\\src\\DataModel");
            Console.ReadKey();
        }
    }
}
```

I can't see to see where to raise a ticket with them any ideas?

**Comment by DBojsen** [comment] 2023-11-14 16:56
I’m afraid you won’t gain anything by raising an issue with Microsoft since it works with the old libraries. 

Unfortunately, breaking changes between versions are to be expected during preview.

**Comment by akhilannan** [comment] 2023-11-15 10:56
> Hi @matt40k
> 
> I'm quite sure that is because [2.21.1](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.1) is using the latest AMO/TOM libraries from Microsoft and they unfortunately include breaking changes from earlier versions for TMDL. (which is still in preview)
> 
> Best workaround now is to open with the last working version (you can use the portable version: [TabularEditor.2.20.2.zip](https://cdn.tabulareditor.com/files/TabularEditor.2.20.2.zip)) and save as model.bim or TE's Save-to-folder format and afterwards reopen in the latest version and save as TMDL again.

Something is wrong in new version of TE. I tried the following:  
1. Saved a TMDL as Model.bim in TE 2.20.2
2. Opened the Model.bim using TE 2.21.1 and saved to a new folder as TMDL
3. Opened the TMDL folder in TE 2.21.1 - I get an error "NullReferenceException encountered while deserializing TMDL: Object reference not set to an instance of an object."

**Comment by mthierba** [comment] 2023-11-15 14:44
@matt40k Escalated your issue to the internal MS engineering team. Will keep you posted here.

**Comment by mthierba** [comment] 2023-11-16 12:43
@matt40k This had been confirmed as a regression, and has already been fixed internally. A bugfix release is on the way! Thanks a lot for reporting the issue 🙏

**Comment by RuiRomano** [comment] 2023-11-20 16:59
The bug as fixed and will be available on the next release (ETA middle of December)
In the meantime you can try the following workarounds:
- Before saving a model to TMDL, if that model has any table(s) with refresh-policy, add a dummy Annotation to the RefreshPolicy object.
- If you have a model that was serialized to TMDL and can't be loaded, remove the colon from the refreshPolicy property

**Comment by matt40k** [comment] 2024-01-03 15:36
@RuiRomano / @mthierba any update when the new version will be released?

**Comment by otykier** [comment] 2024-01-19 12:47
We have a [new version out now](https://github.com/TabularEditor/TabularEditor/releases/tag/2.22.0), which should hopefully solve this issue (feel free to reopen the ticket if the issue isn't solved).

**Closed by otykier** 2024-01-19 12:47 UTC
Labels: bug
