### ISSUE TITLE
Can't connect to a PPU workspace

### ISSUE THREAD

**Issue by jorgemlesteves** [TabularEditor/TabularEditor#1013] opened 2022-07-29 15:02 UTC
Hi Daniel,

With version 2.16.7, I'm unable to connect to a PPU workspace, TE ends up hanging and I have to kill the process in Task Manager.
I'd had to roll back to the previous version V2.16.6.
![image](https://user-images.githubusercontent.com/31868867/181787774-fc4526cc-511b-4240-9f65-d1c97dc0e479.png)

**Comment by otykier** [comment] 2022-07-29 15:03
Duplicate of #1002

**Closed by otykier** 2022-07-29 15:03 UTC

**Comment by jorgemlesteves** [comment] 2022-07-29 15:06
Thanks!
