### ISSUE TITLE
Cannot connect to Azure Analysis Services with 2.16.7

### ISSUE THREAD

**Issue by Teckfahimkanji** [TabularEditor/TabularEditor#1008] opened 2022-07-19 19:06 UTC
**Describe the bug**
I cannot connect to an Azure Analysis Services Server when using 2.16.7 but I can for 2.16.6 / .5 / .4 ...

**To Reproduce**

1. download and do a fresh install of 2.16.6
2. use the servername from your resource to connect to database file->open-from db [asazure://centralus.asazure.windows.net/[myinstance]
3. select your azure authentication user in the OATH prompt
4. select databaase and life goes on as usual
5. download and do a fresh install of 2.16.7
6. repeat 2
7. spins forever (never gets to azure authentication)

**Expected behavior**
ability to connect to azure analysis services database

**Observed behavior**
Cannot connect to azure analysis service database

**Application specifics**
 - Tabular Editor 2.16.7 
 - Semantic Engine used: Azure Analysis Services
 - Model Compatibility Level: 1500
![image](https://user-images.githubusercontent.com/83241428/179829219-538f7afc-2b8f-4d02-bcab-84210b999dfd.png)
![image](https://user-images.githubusercontent.com/83241428/179829255-7171383a-dbb3-46b5-af8c-297a9ac9ec59.png)

**Comment by otykier** [comment] 2022-07-19 19:10
Duplicate of #1002

**Closed by otykier** 2022-07-19 19:10 UTC
Labels: bug

**Comment by Teckfahimkanji** [comment] 2022-07-19 19:49
Confirmed!!
