### ISSUE TITLE
Version 2.16.7 hangs on Windows 2016 Datacenter

### ISSUE THREAD

**Issue by SuChuDom** [TabularEditor/TabularEditor#1011] opened 2022-07-26 10:15 UTC
**Describe the bug**
When upgrading to version 2.16.7, we found that the application hangs when trying to connect to an analysis services server. The operating system (Windows 2016 Datacenter) kills the hanging process, but the GUI stays on, frozen, and has to be terminated via Task Manager.
We uninstalled the latest version and installed 2.16.0, which is working fine.

**To Reproduce**
1. Install version 2.16.7 on our Windows 2016 Datacenter
2. Click "Open model on DB", , and
3. Fill in the server name
4. Choose Azure AD login
5. Click OK
6. See error: no MFA dialogue pops up, the application hangs and minimal error events are log to the Windows event log

**Expected behavior**
A MFA dialogue should pop up, and a list of available models should be displayed.

**Observed behavior**
Occasionally an "application hang" error is logged in the Windows event log

**Application specifics**
 - Tabular Editor 2.16.7
 - Semantic Engine used: Azure Analysis Services

**Additional context**
N/A

**Comment by otykier** [comment] 2022-07-26 10:28
Duplicate of #1002

**Closed by otykier** 2022-07-26 10:28 UTC
Labels: bug
