### ISSUE TITLE
Scripts error on load where namespaces are used

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor#1056] opened 2022-11-20 08:57 UTC
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Scripts don't load at application startup when there is a name space introduced into the script.

**To Reproduce**
1. Add a line into a script to introduce a namespace, e.g. "using Newtonsoft.Json.Linq;"

**Expected behavior**
Macros load as part of application load.

**Observed behavior**
Application doesn't load scripts/macros upon initial load. However, scripts are valid in the editor and once saved show in right click context menu.

**Application specifics**
 - Tabular Editor 2.17.2
 - Power BI Desktop

**Additional context**
[MacroCompilationErrors.log](https://github.com/TabularEditor/TabularEditor/files/10049208/MacroCompilationErrors.log)

**Comment by samaguire** [comment] 2023-01-05 03:49
Looks like the 'r' directive also has the same problem...

![image](https://user-images.githubusercontent.com/62320770/210697594-e0c840f5-7411-4c60-b4b7-fbb92d158ea3.png)

**Comment by otykier** [comment] 2023-02-24 14:52
Hi @samaguire 
Are you still facing this issue? I am not able to reproduce it in 2.17.2. If you can send me your MacroActions.json file from %LocalAppData%\TabularEditor, I'm happy to take another look.

**Comment by samaguire** [comment] 2023-02-25 01:53
Thanks @otykier 

[MacroActions.json.txt](https://github.com/TabularEditor/TabularEditor/files/10830013/MacroActions.json.txt)
[MacroCompilationErrors.log](https://github.com/TabularEditor/TabularEditor/files/10830015/MacroCompilationErrors.log)

The macros are not available when I right click on objects, but show as samples:

![image](https://user-images.githubusercontent.com/62320770/221329606-633b18ca-b832-4626-9eff-3cab23b44933.png)

![image](https://user-images.githubusercontent.com/62320770/221329629-30d8a2e3-6b2a-4e12-ad5b-618ccdb8720b.png)

**Comment by otykier** [comment] 2023-02-27 09:04
Hi @samaguire 

In order to speed up macro compilation during application startup, Tabular Editor combines the code of all macros into a single code module. The problem with this, however, is that if there is a syntax error in one macro, the entire module fails compilation.

There were a number of problems in your MacroActions.json file, that all needs to be fixed before TE can compile the macros at application start-up.

The general issue is that your MacroActions.json file uses `\n` for line breaks within the scripts, where as Tabular Editor expects `\r\n`. Otherwise, it is not able to correctly detect pre-compiler directives (`#r ...`) and `using` statements. This is essentially a bug (or missing feature) in TE, so we'll make sure that's fixed in a future release, but for now you'll have to make sure that any line breaks surrounding the pre-compiler directives and using statements near the top of each script, uses `\r\n`.

In addition to this, there were some specific errors on some of the macros:

1. Tabular Editor's default compiler (which for TE2 is the .NET Framework 4.5 bundled compiler) only supports C# language version 5.0. That means you can't use interpolated strings (`$"{test}"`), unless you've set up [TE2 to use a different compiler](https://docs.tabulareditor.com/te2/Advanced-Scripting.html#compiling-with-roslyn). This applies specifically to your **Create\Parent-child hierarchy** macro.

2. Your **Apply\Best Practice Rules\Add VertiPaq annotations from VPAX** file macro, is missing an assembly reference to `#r "System.IO.Compression.FileSystem.dll"`.

3. Your **Launch\Perspective Editor** macro is missing assembly references to `#r "System.Drawing"` and `#r "System.Net.Http"`.

There may be other issues as well, but these were the first few I noticed when trying to run these scripts within the script editor in TE2. In general, you'll have to make sure that all your scripts can be compiled without error within TE's script editor, before there's any chance for the macros to be successfully compiled during application start up.

Closing this issue, but feel free to open a new ticket if you feel that there are some other issues not covered by this reply.

**Closed by otykier** 2023-02-27 09:04 UTC
Labels: bug

**Comment by samaguire** [comment] 2023-02-27 20:00
@otykier 

Thanks for looking at that. Really appreciate the feedback. 🙏

I'll work through this. I'm using v8.0 which helps.
