### ISSUE TITLE
CTRL + S saves current query, does not synchronize changes to the model

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#939] opened 2021-11-03 13:55 UTC
While writting a DAX query a yellow banner appears with the message "You have made structural changes to the model metadata ... Hit CTRL+S to syncronize" 
But if you click CTRL+S you get the dialog to save the DAX query. 
Also there's no button to synchronize either, at least that I have found. 

Regards!

**Comment by otykier** [comment] 2021-11-03 14:02
Closing this as duplicate of https://github.com/TabularEditor/TabularEditor3/issues/251

(Also, please post Tabular Editor 3 issues on the TE3 GitHub site: https://github.com/TabularEditor/TabularEditor3/issues - this is the site for TE2)

**Closed by otykier** 2021-11-03 14:02 UTC
Labels: bug

**Comment by bernatagulloesbrina** [comment] 2021-11-03 14:19
oups! sorry -- jumped in from google
