### ISSUE TITLE
Q&A breaks with Tabular editor 2.16.1 and Power BI Desktop version 2.94.921.0 64-bit (June, 2021)

### ISSUE THREAD

**Issue by samxlpowerbi** [TabularEditor/TabularEditor#880] opened 2021-07-06 03:34 UTC
!!! Please make sure you're using the latest version of Tabular Editor before submitting a bug !!!

**Describe the bug**
When you use TE to do any operation e.g. create a measure - It breaks Q&A

**To Reproduce**
1. Open TE 2.16.1 - Create a Measure
2. Click Save
3.  Try and insert a Q&A visual 
4.  You get an error - Q&A not supported for this report

**Expected behavior**
Q&A should work

**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor version: [2.16.1]
 - Semantic Engine used: [Power BI Desktop]
 - Model Compatibility Level: []

**Additional context**
When you do anything in Tabular editor for. e.g create a measure - Q&A Stops working

https://user-images.githubusercontent.com/86996123/124538389-2fb7aa00-de39-11eb-810b-4f75e9cd23f5.mp4

**Comment by otykier** [comment] 2021-08-02 10:41
I'm not able to reproduce this issue with the 2.95.983.0 64-bit (July 2021) version of PBI Desktop. Could you try to upgrade to see if this resolves the issue in your case?

**Comment by samxlpowerbi** [comment] 2021-08-02 14:38
I tested this in the newer version of Power BI Desktop as well 2.95.983.0 (30-Jul-2021) 64 Bit - Same problem.
Q&A Breaks even if I just open Tabular Editor 2.16.1 - and click Save without even without doing anything.

**Comment by otykier** [comment] 2021-08-02 17:43
Could you share a minimal .pbix file with a Q&A visual that reproduces this behavior? Thanks!

**Comment by samxlpowerbi** [comment] 2021-08-03 15:03
Hi Daniel - I am uploading a sample pbix file - which reproduces this issue
[SAMPLE_PBIX.zip](https://github.com/TabularEditor/TabularEditor/files/6925099/SAMPLE_PBIX.zip)

**Comment by samxlpowerbi** [comment] 2021-09-04 02:55
Hi Daniel - The issue persists in Ver 2.16.2 - This is making Tabular editor unusable - as almost ever Power BI Desktop file that I create has a Q&A Slide

**Comment by samxlpowerbi** [comment] 2021-09-13 07:02
Hi Daniel - Any update on the above.

**Comment by otykier** [comment] 2021-09-15 07:47
Sorry for the late reply. Could share a pbix file with a working QA visual?

**Comment by samxlpowerbi** [comment] 2021-09-15 11:28
Daniel - That's Great news - Thank you so much

**Comment by otykier** [comment] 2021-09-15 12:26
Fixed in [2.16.3](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.3). Thanks for your patience!

**Closed by otykier** 2021-09-15 12:26 UTC
Labels: bug

**Comment by samxlpowerbi** [comment] 2021-09-16 12:30
Thanks Daniel - I confirmed it works fine in 2.16.3 - Just a quick question - Any way to fix the PBIX File that broke due to the 2.16.2 - Or do I need to recreate ?

**Comment by otykier** [comment] 2021-09-16 13:09
You can fix it by setting "language" to "en-US" within the Content property of the culture, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/8976200/133617779-5d771bfc-564e-4428-99d3-cac1cd701a32.png)

Then, hit Save.

**Comment by samxlpowerbi** [comment] 2021-09-16 14:07
Woooah !! - Thank you Daniel - That worked and has saved me so much of time !
