### ISSUE TITLE
Error when deploying using command line but no error when deploying from Application

### ISSUE THREAD

**Issue by BenT13** [TabularEditor/TabularEditor#1069] opened 2023-01-12 09:38 UTC
Hello,
I'm having the following issue when deploying from command line:

##[error]Deployment failed! Column 'SalesRepNum' in Table 'Sales Rep' contains a duplicate value '91000033' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
2023-01-12T08:05:51.7453150Z
##[error]Cmd.exe exited with code '1'.

But deploying the same model from TE2 application I'm not having any errors

Already checked Column 'SalesRepNum' in Table 'Sales Rep':
- is not a key in the model
- is not referenced in any relationships

Could you please help me figuring out this issue?

Thanks in advance,

Ben

**Comment by mlonsk** [comment] 2023-01-17 09:43
Closing as duplicate of #1069

**Closed by mlonsk** 2023-01-17 09:43 UTC
Labels: question
