### ISSUE TITLE
Columns lose the Ability to Sum after creating calculation group

### ISSUE THREAD

**Issue by Jwinnn** [TabularEditor/TabularEditor#889] opened 2021-07-21 22:08 UTC
I’m using the latest version of Tabular Editor and running into an issue. At times when I create items in a calculation group and save, the columns in my tables lose the ability to sum itself up. I’ll throw the column in a table and it doesn’t sum and it even loses the sigma sign next to the numeric column. They sum up prior to making adjustments within tabular editor. The issue seems to go away after I publish and redownload the .PBIX file.

**Comment by otykier** [comment] 2021-07-22 03:10
Duplicate of #636

**Closed by otykier** 2021-07-22 03:10 UTC
Labels: bug
